// ingredients.js
export const ingredients = {
    harina: { name: "Harina", unit: "kg" },
    azucar: { name: "Azúcar", unit: "kg" },
    polvoHornear: { name: "Royal", unit: "g" },
    leche: { name: "Leche", unit: "l" },
    clavel: { name: "Clavel", unit: "l" },
    bicarbonato: { name: "Bicarbonato", unit: "g" },
    chocolateCrt: { name: "Chocolate Carat", unit: "kg" },
    cafe: { name: "Café", unit: "g" },
    nuez: { name: "Nuez", unit: "g" },
    azucarRef: { name: "Azúcar-refinada", unit: "kg" },
    mantequilla: { name: "Mantequilla", unit: "kg" },
    margarina: { name: "Margarina", unit: "kg" },
    harinaVelvet: { name: "Harina de red velvet", unit: "kg" },
    agua: { name: "Agua", unit: "l" },
    aceite: { name: "Aceite", unit: "ml" },
    lecherabls: { name: "lechera de bolsa", unit: "l" },
    lecherabt: { name: "lechera de bote", unit: "l" },
    quesoDC: { name: "Queso doble crema", unit: "kg" },
    quesoCTG: { name: "Queso cottage", unit: "kg" },
    quesoTPPHI: { name: "Queso tipo philadelphia", unit: "kg" },
    vanilla: { name: "Vanilla", unit: "ml" },
    crema: { name: "Crema", unit: "l" },
    maizena: { name: "Maizena", unit: "g" },
    mantecaVegetal: { name: "Manteca", unit: "g" },
    limones: { name: "Limones", unit: "g" },
};
